# Stage 1: Build the React application
FROM node:20-alpine as build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Receive the API URL as a build argument
ARG VITE_API_URL_TEST
ENV VITE_API_URL=$VITE_API_URL_TEST

RUN npm run build

# Stage 2: Serve the application with Nginx
FROM nginx:alpine

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx template configuration
COPY nginx.conf.template /etc/nginx/conf.d/default.conf.template

# Copy env.sh script
COPY env.sh /docker-entrypoint.d/env.sh
RUN apk add --no-cache dos2unix && dos2unix /docker-entrypoint.d/env.sh
RUN chmod +x /docker-entrypoint.d/env.sh

# Copy and setup docker entrypoint script
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN dos2unix /docker-entrypoint.sh && chmod +x /docker-entrypoint.sh

EXPOSE 80

# Use custom entrypoint to configure nginx and start it
CMD ["/docker-entrypoint.sh"]